version: "3"
services:
    web:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        restart: always
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 
        volumes:
            - static_data:/app/static
            - media_data:/app/media
        env_file:
            - ./.env
        expose:
            - 8000
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 8080:80
        volumes:
          - static_data:/app/static
          - media_data:/app/media
        depends_on:
          - web

volumes:
    static_data:
    media_data: