version: "3"
services:
    web:
        build: ./backend/backend
        command: > 
            sh -c "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - ./backend/backend:/app
            - static_data:/app/static
            - media_data:/app/media
        ports:
            - 80:8000
        env_file:
            - ./.env.dev


volumes:
    static_data:
    media_data: